### ISSUE TITLE
Sensor device: OTA solution

### ISSUE THREAD

**Issue by Timminater** [homonto/ESPnow-MQTT-HomeAssistant-Gateway#1]
Maybe it is possible to make some sort of TCP communication for the sensor devices.

LoraWAN also uses this sort of a software flow for low power consumption

Sensor device wakes up
Sensor devices sends data to gateway
Sensor device listens for gateway ack for 2 seconds

ack from gateway can contain a bit "listen for more data"
when listen for more data is active the sensor listens for additional data

This way the sensor knows data is received by the ack response, if no ack for XX messages, increase transmit power.
Also this way the gateway can send some configuration data to the sensor just after receiving a data packet from a sensor. So it can send a command to a sensor, or some configuration update like "start OTA"

more info on the LoraWAN method is here:
https://lora-developers.semtech.com/documentation/tech-papers-and-guides/lorawan-class-a-devices/

**Comment by homonto** [comment]
thank you for the idea
actually, to receive the message FROM GATEWAY to Sensor it takes much less - I was even thinking this way:
1- send message to gateway that sensor device X is about to perform upgraade
2- gateway keeps this message in the buffer
3- when sensor device wakes up and sends data, send back just after acknowledgement also request: "hey buddy, don't go to sleep - check the new software"

this would require that every sensor waits for the info from gateway before it goes to sleep
currently my sensor device does the full job in 0.2s so changing the code to the one, that sensor waits for info from gateway would increase it probably by 100% to 0.4s
currently my sensor devices are still on 1st charge for already 5 months and still the battery is about 50% - I believe they can work up to 10 months. but increasing the working time by 100% will reduce this battery life by 50%, maybe 35%

So I am not sure what the priority is

Today, to perform OTA, I need to press the button on the sensor device and voila - done - no extra time wasted

**Comment by Timminater** [comment]
I know it uses some extra battery, but even at 50% extra battery usage it still has enough battery life i think.
but besides OTA triggers you can also change devices parameters this way. For example change the send interval.
You can even make this ack optional in the sensor package. So if a sensor sends some info to the gateway this package contains "sensor wants ack" so the gateway can respond. If ack is not enabled on the sensor consumption stays the same as now.

**Comment by homonto** [comment]
you are completely right!
I am not sure yet how to implement it but the easiest would be probably for the sensor to wait for the meaningful confirmation from the receiver

with regards to parameters: with the current version, when the sensor starts first time, it starts the Captive Portal where you can set up some parameters (channel, wifi user/password/, sleep time etc)
it can be also fired up on long press of the button of the sensor (i.e. new wifi credentials are needed or so)

**Comment by homonto** [comment]
DONE!

**Comment by homonto** [comment]
> I know it uses some extra battery, but even at 50% extra battery usage it still has enough battery life i think. but besides OTA triggers you can also change devices parameters this way. For example change the send interval. You can even make this ack optional in the sensor package. So if a sensor sends some info to the gateway this package contains "sensor wants ack" so the gateway can respond. If ack is not enabled on the sensor consumption stays the same as now.
> 
> Even a option to make the "sensor wants ack" bit in the sensor package send only once every XX sends

I did as you suggested ;)
thank you
